/*
 * openshift basic identity
 *
 * openshift basic identity provider
 *
 * API version: 1.0.0
 * Contact: zhu.xiaowei@99cloud.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
	"github.com/rakyll/statik/fs"
	_ "openshift-basic-identity-provider/statik"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	statikFS, err := fs.New()
	if err != nil {
		panic(err)
	}
	staticServer := http.FileServer(statikFS)
	sh := http.StripPrefix("/openshift-basic-identity-provider/1.0.0/api/", staticServer)
	router.PathPrefix("/openshift-basic-identity-provider/1.0.0/api/").Handler(sh)

	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/openshift-basic-identity-provider/1.0.0/user",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/openshift-basic-identity-provider/1.0.0/user/{username}",
		DeleteUser,
	},

	// Route{
	// 	"GetUserByName",
	// 	strings.ToUpper("Get"),
	// 	"/openshift-basic-identity-provider/1.0.0/user/{username}",
	// 	GetUserByName,
	// },

	Route{
		"ListUsers",
		strings.ToUpper("Get"),
		"/openshift-basic-identity-provider/1.0.0/users",
		ListUsers,
	},

	Route{
		"Login",
		strings.ToUpper("Get"),
		"/openshift-basic-identity-provider/1.0.0/auth/token",
		Login,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/openshift-basic-identity-provider/1.0.0/user/{username}",
		UpdateUser,
	},
}
